### PR TITLE
Convert names containing spaces to use underscores

### PR DESCRIPTION
**Pull request by svnv**
Should hopefully close https://github.com/manifoldco/swagger-to-ts/issues/66

### CODE REVIEW

**Comment by ali-alidoust** [comment]
I still get the error. This time where the space containing model name is used as a type.

```
SyntaxError: ';' expected. (1776:17)
  1774 | uri?: string;
  1775 | parameters?: BatchServiceParameterSrv[];
> 1776 | result?: Result model;
       |                 ^
  1777 | }
  1778 | export interface BatchServiceParameterSrv {
  1779 | name?: string;
```

**Comment by svnv** [comment]
Right, added a commit dealing with models being used.

**Comment by dangodev** [comment]
Hey @svnv so sorry for the delay on reviewing. I think my notifications for this repo are a bit messed up—I didn’t see the email go through. Was reviewing things today and noticed this great PR. Bumping the version now; hopefully this wasn’t too inconvenient.

**Comment by dangodev** [comment]
`swagger-to-ts@1.5.0` published to npm 🎉

**Pull request merged**
