### PR TITLE
additionalProperties interpolation, primitive enums

### PR DESCRIPTION
**Pull request by skh-**
if `additionalProperties` is not of a primitive type, the generated file will contain things like `ref` or `array` instead of interpolating that ref or array.  this PR should fix that and #265.

not aware of any side effects, let me know if you can think of any.

### CODE REVIEW

**Comment by skh-** [comment]
had another problem where:

```
type: number
enum:
  - -1
  - 0
  - 1
```

would produce `"-1" | "0" | "1"` when I needed `-1 | 0 | 1`.  

Added fix to this PR.

**Comment by FourF-src** [comment]
https://github.com/manifoldco/swagger-to-ts/issues/278

**Comment by drwpow** [comment]
@all-contributors please add @skh- for code, test

**Comment by skh-** [comment]
@drwpow if you would like maintenance help with the repo feel free to tap me 😄 .

**Comment by drwpow** [comment]
@skh- awesome! Yes I would… as soon as I’m able to get access to the repo again (still locked out of npm deployments and adding contributors at the moment).

**Pull request merged**
