### PR TITLE
Fix support for additionalProperties

### PR DESCRIPTION
**Pull request by Mause**

### CODE REVIEW

**Comment by skh-** [comment]
looks like the same as #266

**Comment by Mause** [comment]
Ah true. It looks like this project is somewhat abandoned though :(

**Comment by drwpow** [comment]
Thanks so much! Sorry for the delay on this. I was maintaining this under the Manifold org, then I left Manifold and lost access. I’m going through all the PRs & issues now and will publish a release soon. Thanks for your patience. 🙏

**Comment by bitsofinfo** [comment]
can this be cut into a release please?

**Comment by Mause** [comment]
I believe it already has been?

**Pull request closed without merging**
